services:
  dev-db:
    image: postgres:alpine
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  server:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    depends_on:
      - dev-db
    ports:
      - ${PORT}:${PORT}
    networks:
      - postgres
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

networks:
  postgres:
    driver: bridge