GET http://localhost:4000/artist

###
GET http://localhost:4000/artist/b4fbb22c-4a68-4fb6-99a8-039c34708fdf

###
POST http://localhost:4000/artist
Content-Type: application/json

{
  "name": "string",
  "grammy": true
}

###
PUT http://localhost:4000/artist/471afc92-e6ae-4544-9308-99fb7e727d4
Content-Type: application/json

{
  "name": "------",
  "grammy": true
}

###

DELETE  http://localhost:4000/artist/61913cda-b329-4c31-8dbd-941c9ce15307
Content-Type: application/json

###