GET http://localhost:4000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjMGUxNjQzOC1kM2MyLTQwYTgtOTAyMy1kOTFlOWIxZGQ0YjMiLCJsb2dpbiI6InN0cmluIiwiaWF0IjoxNjkyMzczMTIwLCJleHAiOjE2OTIzNzY3MjB9.P0eXlsEMr6H80erAz271Qgq_PoM0ytkJIR6Ub72C32I

###
POST http://localhost:4000/auth/signup
Content-Type: application/json
Accept: application/json

{
  "login": "strin23",
  "password": "string"
}

###
POST http://localhost:4000/auth/login
Content-Type: application/json
Accept: application/json

{
  "login": "strin1",
  "password": "string"
}

###
POST http://localhost:4000/auth/refresh
Content-Type: application/json
Accept: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyZDMyYWIwYi1iNTYzLTQwN2ItYWM4OC1mM2I4YzMxZjU0YWQiLCJsb2dpbiI6InN0cmluIiwiaWF0IjoxNjkyMzcyNjc5LCJleHAiOjE2OTI0NTkwNzl9.BS3LvdP1LfM3hq5kG-49_Dpj4-BWW6ilGdMeqYIHMpw"
}

###