GET http://localhost:4000/user
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyNzY4ZTJjOC1hZTMzLTQzN2MtOWJjZi00ZDRlNDg3M2RkMzciLCJsb2dpbiI6InN0cmluIiwiaWF0IjoxNjkyMjczNjQxLCJleHAiOjE2OTIyNzcyNDF9.W_lqVWnyz0ytWxQhqsU1MZgNkPQrXtxa_Sz1NUz8a5s

###
POST http://localhost:4000/signup
Content-Type: application/json
Accept: application/json

{
  "login": "strin1",
  "password": "string"
}

###
POST http://localhost:4000/login
Content-Type: application/json
Accept: application/json

{
  "login": "strin",
  "password": "string"
}

###