GET http://localhost:4000/user
###

GET http://localhost:4000/user/100b509d-9702-4ace-9bde-f509e38023b6
###

POST http://localhost:4000/user
Content-Type: application/json

{
  "login": "strin",
  "password": "string"
}

###

DELETE  http://localhost:4000/user/8a7fa361-4771-47a0-84bb-ebaecfc7434d
Content-Type: application/json


###
